config/routes.rb
Rails.application.routes.draw do
  
  resources :reservations
  get 'home/index'
  root 'home#index'
  resources :librarians
  resources :clients
  resources :authors
  resources :books
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<center>
  <h1 style="color: blue">Bem-vindo(a) à Biblioteca do Senhor Juvenal</h1>
</center>
<h3 style="text-decoration-line: underline"><center><%= link_to "Fazer nova reserva",new_reservation_path %></center></h3>
<h4 style="text-decoration-line: underline"><center><%= link_to "Checar reservas",reservations_path %></center></h4>
<h4><b>Avisos ao bibliotecário</b></h4>
<h5>1.Conferir a documentação do cliente.</h5>
<h5>2.Manusear o livro com cuidado.</h5>
<h5>3.Conferir dados da reserva.</h5>
<h5>4.Se o livro não aparecer na pesquisa da reserva, pode ser que o estoque dele esteja zerado.</h5>
<h5>5.Cheque seu status no canto superior esquerdo, abaixo do seu ícone de usuário.<br/>
  Se ele estiver como "desconectado", veja se a internet está funcionando ou fale com o suporte.</h5>
<h4 class="mobile hidden-md hidden-lg"><%= link_to "Autores",authors_path %></h4>
<h4 class="mobile hidden-md hidden-lg"><%= link_to "Bibliotecários",librarians_path %></h4>
<h4 class="mobile hidden-md hidden-lg"><%= link_to "Categorias",categories_path %></h4>
<h4 class="mobile hidden-md hidden-lg"><%= link_to "Clientes",clients_path %></h4>
<h4 class="mobile hidden-md hidden-lg"><%= link_to "Livros",books_path %></h4>
<h4 class="mobile hidden-md hidden-lg"><%= link_to "Reservas",reservations_path %></h4>