config/routes.rb
Rails.application.routes.draw do
  
  resources :reservations
  get 'home/index'
  root 'home#index'
  resources :librarians
  resources :clients
  resources :authors
  resources :books
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :client
  belongs_to :book
  belongs_to :librarian

  after_create :control_stock

  after_destroy :increase_stock

  def control_stock
    self.book.update(stock: book.stock-1)
  end


  def increase_stock
    self.book.update(stock: book.stock+1)
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
    options_for_select
  end

  # GET /reservations/1/edit
  def edit
    options_for_select
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def options_for_select
      @books_for_select = Book.select{ |x,y| x.stock > 0}
      @clients_for_select = Client.all
      @librarians_for_select = Librarian.all
    end
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:client_id, :book_id, :librarian_id)
    end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation, local: true) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :client_id %>
    <%= collection_select(:reservation,:client_id,@clients_for_select,:id,:name) %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= collection_select(:reservation,:book_id,@books_for_select,:id,:name) %>
  </div>

  <div class="field">
    <%= form.label :librarian_id %>
    <%= collection_select(:reservation,:librarian_id,@librarians_for_select,:id,:email) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editando as Reservas</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Mostrar', @reservation %> |
<%= link_to 'Voltar ', reservations_path %><br/>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Livro</th>
      <th>Bibliotecário</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.client.name %></td>
        <td><%= reservation.book.name %></td>
        <td><%= reservation.librarian.email %></td>
        <td><%= link_to 'Mostrar', reservation %></td>
        <td><%= link_to 'Editar', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destruir', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Reserva', new_reservation_path %> <br/>
<%= link_to 'Voltar ao início', home_index_path %>

app/views/reservations/new.html.erb
<h1>Nova Reserva</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Voltar às reservas', reservations_path %> <br/>
<%= link_to 'Voltar ao início', home_index_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @reservation.client.name %>
</p>

<p>
  <strong>Livro:</strong>
  <%= @reservation.book.name %>
</p>

<p>
  <strong>Bibliotecário:</strong>
  <%= @reservation.librarian.email %>
</p>

<%= link_to 'Editar', edit_reservation_path(@reservation) %> |
<%= link_to 'Voltar às reservas', reservations_path %> |
<%= link_to 'Voltar ao início', home_index_path %>